apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todobackend
  template:
    metadata:
      labels:
        app: todobackend
    spec:
      volumes:
        - name: todo-storage
          persistentVolumeClaim:
            claimName: todo-claim
      containers:
        - name: todobackend
          image: stevemcwin/todo-backend
          volumeMounts:
            - name: todo-storage
              mountPath: /usr/src/app/files
          env:
            - name: DB_HOST
              value: postgres-svc
            - name: DB_NAME
              value: tododb
            - name: DB_USER
              value: tododb
            - name: DB_PORT
              value: "5432"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
