apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todobackend
  ports:
    - port: 6789
      protocol: TCP
      targetPort: 8080
