apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: todo-storage
          persistentVolumeClaim:
            claimName: todo-claim
      containers:
        - name: todoapp
          image: stevemcwin/todo-app
          volumeMounts:
            - name: todo-storage
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: port
            - name: PICTURE_SOURCE
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: picture-source
            - name: PICTURE_WIDTH
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: picture-width
            - name: PICTURE_HEIGHT
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: picture-height
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: backend-url
